In [4]:
import pandas as pd
import numpy as np

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [5]:
mkt_ret = 0.005
df - mkt_ret

           AAPL    MSFT   TSLA    LULU
20201201 -0.015  0.0250  0.045  0.0000
20201202  0.010  0.0000 -0.055 -0.0075
20201203 -0.030 -0.0035 -0.025  0.0050
20201204 -0.035  0.0100  0.025  0.0050

In [7]:
df>0

           AAPL  MSFT   TSLA   LULU
20201201  False  True   True   True
20201202   True  True  False  False
20201203  False  True  False   True
20201204  False  True   True   True

In [8]:
np.abs(df)

           AAPL    MSFT  TSLA    LULU
20201201  0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050  0.05  0.0025
20201203  0.025  0.0015  0.02  0.0100
20201204  0.030  0.0150  0.03  0.0100

In [11]:
def thresh(x):
    if np.abs(x) > 0.005:
        return x
    else:
        return 0



df.applymap(thresh)

C:\Users\super\AppData\Local\Temp\ipykernel_25996\1424824164.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(thresh)

           AAPL   MSFT  TSLA  LULU
20201201 -0.010  0.030  0.05  0.00
20201202  0.015  0.000 -0.05  0.00
20201203 -0.025  0.000 -0.02  0.01
20201204 -0.030  0.015  0.03  0.01

In [12]:
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [14]:
def max_minus_min(ser):
    return ser.max()-ser.min()
float(max_minus_min(df['AAPL']))

0.045

In [15]:
df.apply(max_minus_min)

AAPL    0.0450
MSFT    0.0285
TSLA    0.1000
LULU    0.0125
dtype: float64

In [16]:
df.apply(max_minus_min, axis = 1)

20201201    0.060
20201202    0.065
20201203    0.035
20201204    0.060
dtype: float64

In [17]:
def min_and_max(ser):
    return pd.Series([ser.min(), ser.max()], index=['min','max'])

df.apply(min_and_max)

      AAPL    MSFT  TSLA    LULU
min -0.030  0.0015 -0.05 -0.0025
max  0.015  0.0300  0.05  0.0100