In [69]:
import pandas as pd
import numpy as np

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [70]:
mkt_ret = 0.005
df - mkt_ret

           AAPL    MSFT   TSLA    LULU
20201201 -0.015  0.0250  0.045  0.0000
20201202  0.010  0.0000 -0.055 -0.0075
20201203 -0.030 -0.0035 -0.025  0.0050
20201204 -0.035  0.0100  0.025  0.0050

In [71]:
df>0

           AAPL  MSFT   TSLA   LULU
20201201  False  True   True   True
20201202   True  True  False  False
20201203  False  True  False   True
20201204  False  True   True   True

In [72]:
np.abs(df)

           AAPL    MSFT  TSLA    LULU
20201201  0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050  0.05  0.0025
20201203  0.025  0.0015  0.02  0.0100
20201204  0.030  0.0150  0.03  0.0100

In [73]:
def thresh(x):
    if np.abs(x) > 0.005:
        return x
    else:
        return 0



df.applymap(thresh)

C:\Users\super\AppData\Local\Temp\ipykernel_26716\1424824164.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(thresh)

           AAPL   MSFT  TSLA  LULU
20201201 -0.010  0.030  0.05  0.00
20201202  0.015  0.000 -0.05  0.00
20201203 -0.025  0.000 -0.02  0.01
20201204 -0.030  0.015  0.03  0.01

In [74]:
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [75]:
def max_minus_min(ser):
    return ser.max()-ser.min()
float(max_minus_min(df['AAPL']))

0.045

In [76]:
df.apply(max_minus_min)

AAPL    0.0450
MSFT    0.0285
TSLA    0.1000
LULU    0.0125
dtype: float64

In [77]:
df.apply(max_minus_min, axis = 1)

20201201    0.060
20201202    0.065
20201203    0.035
20201204    0.060
dtype: float64

In [78]:
def min_and_max(ser):
    return pd.Series([ser.min(), ser.max()], index=['min','max'])

df.apply(min_and_max)

      AAPL    MSFT  TSLA    LULU
min -0.030  0.0015 -0.05 -0.0025
max  0.015  0.0300  0.05  0.0100

In [79]:

df.mean()

AAPL   -0.012500
MSFT    0.012875
TSLA    0.002500
LULU    0.005625
dtype: float64

In [80]:
df.mean(axis=1)

20201201    0.018750
20201202   -0.008125
20201203   -0.008375
20201204    0.006250
dtype: float64

In [81]:
df.index

Index(['20201201', '20201202', '20201203', '20201204'], dtype='object')

In [82]:
df.shape

(4, 4)

In [83]:
avg = {}
for x in df.index:
    tot = 0
    for y in df.columns:
        tot += df.loc[x, y]
    avg[x]=tot/df.shape[0]
avg = pd.Series(avg)
avg

20201201    0.018750
20201202   -0.008125
20201203   -0.008375
20201204    0.006250
dtype: float64

In [84]:
df.rank()

          AAPL  MSFT  TSLA  LULU
20201201   3.0   4.0   4.0   2.0
20201202   4.0   2.0   1.0   1.0
20201203   2.0   1.0   2.0   3.5
20201204   1.0   3.0   3.0   3.5

In [85]:
df.rank(axis=1)

          AAPL  MSFT  TSLA  LULU
20201201   1.0   3.0   4.0   2.0
20201202   4.0   3.0   1.0   2.0
20201203   1.0   3.0   2.0   4.0
20201204   1.0   3.0   4.0   2.0

In [86]:
df.describe()

           AAPL      MSFT      TSLA      LULU
count  4.000000  4.000000  4.000000  4.000000
mean  -0.012500  0.012875  0.002500  0.005625
std    0.020207  0.012770  0.045735  0.005907
min   -0.030000  0.001500 -0.050000 -0.002500
25%   -0.026250  0.004125 -0.027500  0.003125
50%   -0.017500  0.010000  0.005000  0.007500
75%   -0.003750  0.018750  0.035000  0.010000
max    0.015000  0.030000  0.050000  0.010000

In [87]:
df.corr()

          AAPL      MSFT      TSLA      LULU
AAPL  1.000000 -0.088811 -0.550041 -0.994808
MSFT -0.088811  1.000000  0.879688  0.056617
TSLA -0.550041  0.879688  1.000000  0.516655
LULU -0.994808  0.056617  0.516655  1.000000

In [88]:
df.cov()

          AAPL      MSFT      TSLA      LULU
AAPL  0.000408 -0.000023 -0.000508 -0.000119
MSFT -0.000023  0.000163  0.000514  0.000004
TSLA -0.000508  0.000514  0.002092  0.000140
LULU -0.000119  0.000004  0.000140  0.000035

In [89]:
mkt_ret = pd.Series([0.01, 0.02, 0.03, 0.04], index=['20201201','20201202','20201203','20201204'])
df.corrwith(mkt_ret)

AAPL   -0.638877
MSFT   -0.490331
TSLA   -0.084684
LULU    0.600994
dtype: float64

In [90]:
import pandas as pd

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df1=pd.DataFrame(data,index=index,columns=columns)
df1

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [91]:
df2 = -1.0*df1

In [92]:
df1 + df2

          AAPL  MSFT  TSLA  LULU
20201201   0.0   0.0   0.0   0.0
20201202   0.0   0.0   0.0   0.0
20201203   0.0   0.0   0.0   0.0
20201204   0.0   0.0   0.0   0.0

In [93]:
# 2D list or NumPy array

index=['20201201','20201202','20201203']
columns = ['AAPL','MSFT']

data = [[-0.005,0.01],
        [-0.025,0.0075],
        [-0.005,0.015]]
df3=pd.DataFrame(data,index=index,columns=columns)
df3

           AAPL    MSFT
20201201 -0.005  0.0100
20201202 -0.025  0.0075
20201203 -0.005  0.0150

In [94]:
df1+df3

           AAPL  LULU    MSFT  TSLA
20201201 -0.015   NaN  0.0400   NaN
20201202 -0.010   NaN  0.0125   NaN
20201203 -0.030   NaN  0.0165   NaN
20201204    NaN   NaN     NaN   NaN

In [95]:
df1.add(df3, fill_value=0)

           AAPL    LULU    MSFT  TSLA
20201201 -0.015  0.0050  0.0400  0.05
20201202 -0.010 -0.0025  0.0125 -0.05
20201203 -0.030  0.0100  0.0165 -0.02
20201204 -0.030  0.0100  0.0150  0.03

In [96]:
df1 > df2

           AAPL  MSFT   TSLA   LULU
20201201  False  True   True   True
20201202   True  True  False  False
20201203  False  True  False   True
20201204  False  True   True   True

In [97]:
(df1>0) & (df2>0)

           AAPL   MSFT   TSLA   LULU
20201201  False  False  False  False
20201202  False  False  False  False
20201203  False  False  False  False
20201204  False  False  False  False

In [98]:
(df1>0) | (df2>0)

          AAPL  MSFT  TSLA  LULU
20201201  True  True  True  True
20201202  True  True  True  True
20201203  True  True  True  True
20201204  True  True  True  True

In [99]:
df1

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [100]:
ser = pd.Series({'AAPL':100, 'MSFT':200, 'TSLA':50})
df1 * ser

          AAPL  LULU  MSFT  TSLA
20201201  -1.0   NaN   6.0   2.5
20201202   1.5   NaN   1.0  -2.5
20201203  -2.5   NaN   0.3  -1.0
20201204  -3.0   NaN   3.0   1.5

In [101]:
df1

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [138]:
ser = pd.Series({'20201201':100,'20201203':200})
df1.mul(ser,axis=0)

          AAPL  MSFT  TSLA  LULU
20201201  -1.0   3.0   5.0   0.5
20201202   NaN   NaN   NaN   NaN
20201203  -5.0   0.3  -4.0   2.0
20201204   NaN   NaN   NaN   NaN