In [1]:
import pandas as pd 
import numpy as np
ser = pd.Series({'AAPL':0.01,'MSFT':-0.01,'TSLA':np.nan,'LULU':0.005})

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[np.nan,0.03,0.05,0.005],
      [np.nan,np.nan,-0.05,-0.0025],
      [np.nan,np.nan,np.nan,np.nan],
      [np.nan,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [2]:
nan = np.nan

In [3]:
nan

nan

In [5]:
pd.isnull(nan)

True

In [6]:
ser

AAPL    0.010
MSFT   -0.010
TSLA      NaN
LULU    0.005
dtype: float64

In [7]:
pd.isnull(ser)

AAPL    False
MSFT    False
TSLA     True
LULU    False
dtype: bool

In [8]:
ser.isnull()

AAPL    False
MSFT    False
TSLA     True
LULU    False
dtype: bool

In [10]:
ser.notnull()

AAPL     True
MSFT     True
TSLA    False
LULU     True
dtype: bool

In [11]:
ser.count()

np.int64(3)

In [12]:
df.isnull()

          AAPL   MSFT   TSLA   LULU
20201201  True  False  False  False
20201202  True   True  False  False
20201203  True   True   True   True
20201204  True  False  False  False

In [13]:
df.notnull()

           AAPL   MSFT   TSLA   LULU
20201201  False   True   True   True
20201202  False  False   True   True
20201203  False  False  False  False
20201204  False   True   True   True

In [14]:
df.count()

AAPL    0
MSFT    2
TSLA    3
LULU    3
dtype: int64

In [15]:
ser[ser.notnull()]

AAPL    0.010
MSFT   -0.010
LULU    0.005
dtype: float64

In [16]:
ser.dropna()

AAPL    0.010
MSFT   -0.010
LULU    0.005
dtype: float64

In [17]:
df.dropna()

Empty DataFrame
Columns: [AAPL, MSFT, TSLA, LULU]
Index: []

In [18]:
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [19]:
df.dropna(how='all')

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201204   NaN  0.015  0.03  0.0100

In [20]:
df.dropna(thresh=3)

          AAPL   MSFT  TSLA   LULU
20201201   NaN  0.030  0.05  0.005
20201204   NaN  0.015  0.03  0.010

In [21]:
df.dropna(axis=1, thresh=3)

          TSLA    LULU
20201201  0.05  0.0050
20201202 -0.05 -0.0025
20201203   NaN     NaN
20201204  0.03  0.0100

In [22]:
ser

AAPL    0.010
MSFT   -0.010
TSLA      NaN
LULU    0.005
dtype: float64

In [23]:
ser

AAPL    0.010
MSFT   -0.010
TSLA      NaN
LULU    0.005
dtype: float64

In [25]:
ser.fillna(0)

AAPL    0.010
MSFT   -0.010
TSLA    0.000
LULU    0.005
dtype: float64

In [26]:
df

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [27]:
df.fillna(0)

          AAPL   MSFT  TSLA    LULU
20201201   0.0  0.030  0.05  0.0050
20201202   0.0  0.000 -0.05 -0.0025
20201203   0.0  0.000  0.00  0.0000
20201204   0.0  0.015  0.03  0.0100

In [28]:
df.fillna({'AAPL':0.02, 'TSLA':0.02,'MSFT':0.02, 'LULU':0.01})

          AAPL   MSFT  TSLA    LULU
20201201  0.02  0.030  0.05  0.0050
20201202  0.02  0.020 -0.05 -0.0025
20201203  0.02  0.020  0.02  0.0100
20201204  0.02  0.015  0.03  0.0100

In [30]:
avg = df.mean()
avg

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [31]:
df.fillna(avg)

          AAPL    MSFT  TSLA      LULU
20201201   NaN  0.0300  0.05  0.005000
20201202   NaN  0.0225 -0.05 -0.002500
20201203   NaN  0.0225  0.01  0.004167
20201204   NaN  0.0150  0.03  0.010000

In [32]:
df.fillna(method='ffill',limit=1)
df

C:\Users\super\AppData\Local\Temp\ipykernel_18580\3165326039.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=1)

          AAPL   MSFT  TSLA    LULU
20201201   NaN  0.030  0.05  0.0050
20201202   NaN    NaN -0.05 -0.0025
20201203   NaN    NaN   NaN     NaN
20201204   NaN  0.015  0.03  0.0100

In [33]:
df.mean()

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [34]:
df.fillna(0).sum()/df.count()

AAPL         NaN
MSFT    0.022500
TSLA    0.010000
LULU    0.004167
dtype: float64

In [35]:
np.mean(df.values, axis = 1)

array([nan, nan, nan, nan])

In [36]:
df.rank()

          AAPL  MSFT  TSLA  LULU
20201201   NaN   2.0   3.0   2.0
20201202   NaN   NaN   1.0   1.0
20201203   NaN   NaN   NaN   NaN
20201204   NaN   1.0   2.0   3.0