In [63]:
import pandas as pd 
import numpy as np 

univ = ['SPY','TLT','VXX','QQQ']
dates = ['20210105','20210106','20210107','20210108','20210109']

In [64]:
earnings = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
ret_prev = pd.DataFrame(np.random.randn(5,4), index=dates,columns=univ)
pe = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)
analyst_est = pd.DataFrame( np.random.randn(5,4), index=dates,columns=univ)

In [65]:
pe

               SPY       TLT       VXX       QQQ
20210105  1.015472  0.237897 -0.698608  0.339629
20210106  3.113903  0.266332 -0.362278 -0.728148
20210107 -0.791653  2.011116  0.978680  0.395747
20210108  0.449439  1.451770  0.761566 -0.559850
20210109 -1.255732  2.092364 -0.412034  1.474584

In [66]:
data = {}
data['earnings']=earnings
data['ret_prev']=ret_prev
data['pe'] = pe
data['analyst_est']= analyst_est

In [67]:
multi=pd.concat(data)
multi

                           SPY       TLT       VXX       QQQ
earnings    20210105 -0.866170 -0.030660 -0.138688 -1.302395
            20210106  0.380314 -0.984249  0.183665 -1.427913
            20210107  1.785070  0.253131  0.600730 -1.281410
            20210108 -1.814999  0.403697  0.489299 -1.073718
            20210109  0.845341 -0.724967 -0.053412  0.315849
ret_prev    20210105 -1.188746  0.678978  1.641988  0.122792
            20210106 -0.471591  0.870751 -0.711751  0.347914
            20210107  0.043311 -0.050606 -0.267824  0.133914
            20210108 -0.019873  0.434230  0.658302  0.479017
            20210109 -0.875962  0.126090 -1.617019  0.149826
pe          20210105  1.015472  0.237897 -0.698608  0.339629
            20210106  3.113903  0.266332 -0.362278 -0.728148
            20210107 -0.791653  2.011116  0.978680  0.395747
            20210108  0.449439  1.451770  0.761566 -0.559850
            20210109 -1.255732  2.092364 -0.412034  1.474584
analyst_est 20210105  0.281836  0.109362  2.215023 -0.599724
            20210106  1.143377  1.491093 -0.034894  1.019691
            20210107  1.649826 -0.391848 -0.204350  0.369040
            20210108 -0.855739  2.844791 -0.013375  0.312100
            20210109  0.346112  0.711851  0.333879  0.240507

In [68]:
multi.loc['pe']

               SPY       TLT       VXX       QQQ
20210105  1.015472  0.237897 -0.698608  0.339629
20210106  3.113903  0.266332 -0.362278 -0.728148
20210107 -0.791653  2.011116  0.978680  0.395747
20210108  0.449439  1.451770  0.761566 -0.559850
20210109 -1.255732  2.092364 -0.412034  1.474584

In [69]:
multi.loc['ret_prv':'analyst_est']

Empty DataFrame
Columns: [SPY, TLT, VXX, QQQ]
Index: []

In [70]:
multi.loc[('ret_prev','20210107'),['SPY','TLT']]

SPY    0.043311
TLT   -0.050606
Name: (ret_prev, 20210107), dtype: float64

In [71]:
ser = multi['SPY']
ser

earnings     20210105   -0.866170
             20210106    0.380314
             20210107    1.785070
             20210108   -1.814999
             20210109    0.845341
ret_prev     20210105   -1.188746
             20210106   -0.471591
             20210107    0.043311
             20210108   -0.019873
             20210109   -0.875962
pe           20210105    1.015472
             20210106    3.113903
             20210107   -0.791653
             20210108    0.449439
             20210109   -1.255732
analyst_est  20210105    0.281836
             20210106    1.143377
             20210107    1.649826
             20210108   -0.855739
             20210109    0.346112
Name: SPY, dtype: float64

In [72]:
ser.unstack(level=0)

          earnings  ret_prev        pe  analyst_est
20210105 -0.866170 -1.188746  1.015472     0.281836
20210106  0.380314 -0.471591  3.113903     1.143377
20210107  1.785070  0.043311 -0.791653     1.649826
20210108 -1.814999 -0.019873  0.449439    -0.855739
20210109  0.845341 -0.875962 -1.255732     0.346112

In [73]:
ser.unstack(level=0).stack()

20210105  earnings      -0.866170
          ret_prev      -1.188746
          pe             1.015472
          analyst_est    0.281836
20210106  earnings       0.380314
          ret_prev      -0.471591
          pe             3.113903
          analyst_est    1.143377
20210107  earnings       1.785070
          ret_prev       0.043311
          pe            -0.791653
          analyst_est    1.649826
20210108  earnings      -1.814999
          ret_prev      -0.019873
          pe             0.449439
          analyst_est   -0.855739
20210109  earnings       0.845341
          ret_prev      -0.875962
          pe            -1.255732
          analyst_est    0.346112
dtype: float64

In [74]:
multi=pd.concat(data, axis=1)
multi

          earnings                                ret_prev            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105 -0.866170 -0.030660 -0.138688 -1.302395 -1.188746  0.678978
20210106  0.380314 -0.984249  0.183665 -1.427913 -0.471591  0.870751
20210107  1.785070  0.253131  0.600730 -1.281410  0.043311 -0.050606
20210108 -1.814999  0.403697  0.489299 -1.073718 -0.019873  0.434230
20210109  0.845341 -0.724967 -0.053412  0.315849 -0.875962  0.126090

                                    pe                                \
               VXX       QQQ       SPY       TLT       VXX       QQQ
20210105  1.641988  0.122792  1.015472  0.237897 -0.698608  0.339629
20210106 -0.711751  0.347914  3.113903  0.266332 -0.362278 -0.728148
20210107 -0.267824  0.133914 -0.791653  2.011116  0.978680  0.395747
20210108  0.658302  0.479017  0.449439  1.451770  0.761566 -0.559850
20210109 -1.617019  0.149826 -1.255732  2.092364 -0.412034  1.474584

         analyst_est
                 SPY       TLT       VXX       QQQ
20210105    0.281836  0.109362  2.215023 -0.599724
20210106    1.143377  1.491093 -0.034894  1.019691
20210107    1.649826 -0.391848 -0.204350  0.369040
20210108   -0.855739  2.844791 -0.013375  0.312100
20210109    0.346112  0.711851  0.333879  0.240507

In [75]:
multi['pe']

               SPY       TLT       VXX       QQQ
20210105  1.015472  0.237897 -0.698608  0.339629
20210106  3.113903  0.266332 -0.362278 -0.728148
20210107 -0.791653  2.011116  0.978680  0.395747
20210108  0.449439  1.451770  0.761566 -0.559850
20210109 -1.255732  2.092364 -0.412034  1.474584

In [76]:
multi[['pe','earnings']]

                pe                                earnings            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  1.015472  0.237897 -0.698608  0.339629 -0.866170 -0.030660
20210106  3.113903  0.266332 -0.362278 -0.728148  0.380314 -0.984249
20210107 -0.791653  2.011116  0.978680  0.395747  1.785070  0.253131
20210108  0.449439  1.451770  0.761566 -0.559850 -1.814999  0.403697
20210109 -1.255732  2.092364 -0.412034  1.474584  0.845341 -0.724967


               VXX       QQQ
20210105 -0.138688 -1.302395
20210106  0.183665 -1.427913
20210107  0.600730 -1.281410
20210108  0.489299 -1.073718
20210109 -0.053412  0.315849

In [77]:
multi.swaplevel(0,1,1)

,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ,SPY,TLT,VXX,QQQ
,earnings,earnings,earnings,earnings,ret_prev,ret_prev,ret_prev,ret_prev,pe,pe,pe,pe,analyst_est,analyst_est,analyst_est,analyst_est
20210105,-0.866170,-0.030660,-0.138688,-1.302395,-1.188746,0.678978,1.641988,0.122792,1.015472,0.237897,-0.698608,0.339629,0.281836,0.109362,2.215023,-0.599724
20210106,0.380314,-0.984249,0.183665,-1.427913,-0.471591,0.870751,-0.711751,0.347914,3.113903,0.266332,-0.362278,-0.728148,1.143377,1.491093,-0.034894,1.019691
20210107,1.785070,0.253131,0.600730,-1.281410,0.043311,-0.050606,-0.267824,0.133914,-0.791653,2.011116,0.978680,0.395747,1.649826,-0.391848,-0.204350,0.369040
20210108,-1.814999,0.403697,0.489299,-1.073718,-0.019873,0.434230,0.658302,0.479017,0.449439,1.451770,0.761566,-0.559850,-0.855739,2.844791,-0.013375,0.312100
20210109,0.845341,-0.724967,-0.053412,0.315849,-0.875962,0.126090,-1.617019,0.149826,-1.255732,2.092364,-0.412034,1.474584,0.346112,0.711851,0.333879,0.240507

In [98]:
multi.swaplevel(0,1,1).sort_index(axis=1)

                 QQQ                                       SPY            \
         analyst_est  earnings        pe  ret_prev analyst_est  earnings
20210105   -2.593930 -1.306274  0.371194  0.184148    1.393304  0.726721
20210106   -0.130611 -0.921761 -0.480165 -2.562067    0.972735 -0.159607
20210107   -0.435757 -0.947300  0.341158  0.985634   -0.441915 -0.036723
20210108    1.804698  0.191784  0.893170  1.481577    0.307764  0.881476
20210109   -1.101006 -0.565711 -0.235379 -1.344751    1.864714 -0.927459

                                     TLT                                \
                pe  ret_prev analyst_est  earnings        pe  ret_prev
20210105  2.269718  0.385508    1.851526  1.062916 -0.326403 -0.279735
20210106 -1.525126  0.438490    0.812169  0.893821  1.928276  0.794792
20210107 -0.564024  1.285029   -0.108259  0.079662  0.245137 -0.669442
20210108  0.492635  0.455356    0.630255 -0.679325 -0.932760  0.475870
20210109  0.071092  0.113760   -0.344577  0.991496 -1.500724 -0.443602

                 VXX
         analyst_est  earnings        pe  ret_prev
20210105   -0.732726 -1.202092 -0.600869  0.636631
20210106   -1.060858  1.378499  0.141196 -0.068717
20210107    1.036437  1.685000  0.190645  1.392313
20210108   -0.540120 -0.319968  0.473481  0.265096
20210109   -0.948807 -0.053012  2.275469 -1.490433

In [102]:
multi.groupby(level=0).sum()

          earnings                                ret_prev            \
               SPY       TLT       VXX       QQQ       SPY       TLT
20210105  0.726721  1.062916 -1.202092 -1.306274  0.385508 -0.279735
20210106 -0.159607  0.893821  1.378499 -0.921761  0.438490  0.794792
20210107 -0.036723  0.079662  1.685000 -0.947300  1.285029 -0.669442
20210108  0.881476 -0.679325 -0.319968  0.191784  0.455356  0.475870
20210109 -0.927459  0.991496 -0.053012 -0.565711  0.113760 -0.443602

                                    pe                                \
               VXX       QQQ       SPY       TLT       VXX       QQQ
20210105  0.636631  0.184148  2.269718 -0.326403 -0.600869  0.371194
20210106 -0.068717 -2.562067 -1.525126  1.928276  0.141196 -0.480165
20210107  1.392313  0.985634 -0.564024  0.245137  0.190645  0.341158
20210108  0.265096  1.481577  0.492635 -0.932760  0.473481  0.893170
20210109 -1.490433 -1.344751  0.071092 -1.500724  2.275469 -0.235379

         analyst_est
                 SPY       TLT       VXX       QQQ
20210105    1.393304  1.851526 -0.732726 -2.593930
20210106    0.972735  0.812169 -1.060858 -0.130611
20210107   -0.441915 -0.108259  1.036437 -0.435757
20210108    0.307764  0.630255 -0.540120  1.804698
20210109    1.864714 -0.344577 -0.948807 -1.101006