In [1]:
import pandas as pd

In [2]:
# 2D list or NumPy array

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [3]:
# Dict of equal length lists or NumPy arrays

data = {'AAPL':[-0.01,0.015,-0.025,-0.03],
        'MSFT':[0.03,0.005,0.0015,0.015],
        'TSLA':[0.05,-0.05,-0.2,0.03],
        'LULU':[0.005,-0.0025,0.01,0.01]
       }

index=['20201201','20201202','20201203','20201204']
df=pd.DataFrame(data,index=index)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.20  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [4]:
# Dict of Series
index=['20201201','20201202','20201203','20201204']

data={}
data['AAPL'] = pd.Series([-0.01,0.015,-0.025,-0.03],index=index)
data['MSFT'] = pd.Series([0.03,0.005,0.0015,0.015],index=index)
data['TSLA'] = pd.Series([0.05,-0.05,-0.2,0.03],index=index)
data['LULU'] = pd.Series([0.005,-0.0025,0.01,0.01],index=index)

df=pd.DataFrame(data)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.20  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [5]:
# incrementally adding columns
index=['20201201','20201202','20201203','20201204']
df = pd.DataFrame()

df['AAPL'] = pd.Series([-0.01,0.015,-0.025,-0.03],index=index)
df['MSFT'] = pd.Series([0.03,0.005,0.0015,0.015],index=index)
df['TSLA'] = pd.Series([0.05,-0.05,-0.2,0.03],index=index)
df['LULU'] = pd.Series([0.005,-0.0025,0.01,0.01],index=index)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.20  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [6]:
# get data
df.values

array([[-0.01  ,  0.03  ,  0.05  ,  0.005 ],
       [ 0.015 ,  0.005 , -0.05  , -0.0025],
       [-0.025 ,  0.0015, -0.2   ,  0.01  ],
       [-0.03  ,  0.015 ,  0.03  ,  0.01  ]])

In [7]:
# get columns
df.columns

Index(['AAPL', 'MSFT', 'TSLA', 'LULU'], dtype='object')

In [8]:
# get rows
df.index

Index(['20201201', '20201202', '20201203', '20201204'], dtype='object')

In [9]:
import pandas as pd

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [10]:
df['AAPL']

20201201   -0.010
20201202    0.015
20201203   -0.025
20201204   -0.030
Name: AAPL, dtype: float64

In [11]:
df.loc['20201201']

AAPL   -0.010
MSFT    0.030
TSLA    0.050
LULU    0.005
Name: 20201201, dtype: float64

In [12]:
print(df['TSLA']['20201203'])

-0.02

In [13]:
print(df.loc['20201203']['TSLA'])

-0.02

In [14]:
df.loc[['20201201','20201203'],['TSLA','AAPL']]

          TSLA   AAPL
20201201  0.05 -0.010
20201203 -0.02 -0.025

In [15]:
df.loc['20201201':'20201203','TSLA']

20201201    0.05
20201202   -0.05
20201203   -0.02
Name: TSLA, dtype: float64

In [16]:
df.loc[df['TSLA']>0,['TSLA','AAPL']]

          TSLA  AAPL
20201201  0.05 -0.01
20201204  0.03 -0.03

In [17]:
df.loc[:,df.loc['20201203']>0]

            MSFT    LULU
20201201  0.0300  0.0050
20201202  0.0050 -0.0025
20201203  0.0015  0.0100
20201204  0.0150  0.0100

In [18]:
df[df['AAPL']<0]

           AAPL    MSFT  TSLA   LULU
20201201 -0.010  0.0300  0.05  0.005
20201203 -0.025  0.0015 -0.02  0.010
20201204 -0.030  0.0150  0.03  0.010

In [19]:
df[df<0]

           AAPL  MSFT  TSLA    LULU
20201201 -0.010   NaN   NaN     NaN
20201202    NaN   NaN -0.05 -0.0025
20201203 -0.025   NaN -0.02     NaN
20201204 -0.030   NaN   NaN     NaN

In [20]:
df.loc['20201203','TSLA'] = 0.03
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015  0.03  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [21]:
df['TSLA'] = 0
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300     0  0.0050
20201202  0.015  0.0050     0 -0.0025
20201203 -0.025  0.0015     0  0.0100
20201204 -0.030  0.0150     0  0.0100

In [22]:
df.loc[df['AAPL']<0, 'AAPL'] = 0

In [23]:
df

           AAPL    MSFT  TSLA    LULU
20201201  0.000  0.0300     0  0.0050
20201202  0.015  0.0050     0 -0.0025
20201203  0.000  0.0015     0  0.0100
20201204  0.000  0.0150     0  0.0100

In [24]:
df[df<0] = 0
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300     0  0.005
20201202  0.015  0.0050     0  0.000
20201203  0.000  0.0015     0  0.010
20201204  0.000  0.0150     0  0.010

In [25]:
df['TSLA'] = [0.05,-0.05,-0.2,0.03]
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300  0.05  0.005
20201202  0.015  0.0050 -0.05  0.000
20201203  0.000  0.0015 -0.20  0.010
20201204  0.000  0.0150  0.03  0.010

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300  0.05  0.005
20201202  0.015  0.0050 -0.05  0.000
20201203  0.000  0.0015 -0.20  0.010
20201204  0.000  0.0150  0.10  0.010

In [28]:
# set column using series > automatically aligns indices
# doesn't need to be the same size
tsla = pd.Series({'20201204':0.01,'20201201':0.02,'20201202':0.04})
tsla

20201204    0.01
20201201    0.02
20201202    0.04
dtype: float64

In [29]:
df['TSLA'] = tsla
df

           AAPL    MSFT  TSLA   LULU
20201201  0.000  0.0300  0.02  0.005
20201202  0.015  0.0050  0.04  0.000
20201203  0.000  0.0015   NaN  0.010
20201204  0.000  0.0150  0.01  0.010

In [30]:
df.loc['20201202'] = [0.01,0.02,0.03,0.04]
df

          AAPL    MSFT  TSLA   LULU
20201201  0.00  0.0300  0.02  0.005
20201202  0.01  0.0200  0.03  0.040
20201203  0.00  0.0015   NaN  0.010
20201204  0.00  0.0150  0.01  0.010

In [31]:
df.loc[['20201202', '20201203'],['AAPL','TSLA']]

          AAPL  TSLA
20201202  0.01  0.03
20201203  0.00   NaN

In [32]:
df.loc[['20201202', '20201203'],['AAPL','TSLA']] = [[0.01,-0.01],[0.02,0.03]]

In [33]:
df

          AAPL    MSFT  TSLA   LULU
20201201  0.00  0.0300  0.02  0.005
20201202  0.01  0.0200 -0.01  0.040
20201203  0.02  0.0015  0.03  0.010
20201204  0.00  0.0150  0.01  0.010

In [34]:
df['XOM'] = [0.01,0.005,-0.005,0.025]
df

          AAPL    MSFT  TSLA   LULU    XOM
20201201  0.00  0.0300  0.02  0.005  0.010
20201202  0.01  0.0200 -0.01  0.040  0.005
20201203  0.02  0.0015  0.03  0.010 -0.005
20201204  0.00  0.0150  0.01  0.010  0.025

In [35]:
df.loc['20201205'] = [-0.01,0.015,0.03,0.05,-0.01]

In [36]:
df

          AAPL    MSFT  TSLA   LULU    XOM
20201201  0.00  0.0300  0.02  0.005  0.010
20201202  0.01  0.0200 -0.01  0.040  0.005
20201203  0.02  0.0015  0.03  0.010 -0.005
20201204  0.00  0.0150  0.01  0.010  0.025
20201205 -0.01  0.0150  0.03  0.050 -0.010