In [1]:
import pandas as pd

index=['20201201','20201202','20201203','20201204']
columns = ['AAPL','MSFT','TSLA','LULU']

data=[[-0.01,0.03,0.05,0.005],
      [0.015,0.005,-0.05,-0.0025],
      [-0.025,0.0015,-0.02,0.01],
      [-0.03,0.015,0.03,0.01]]

df=pd.DataFrame(data,index=index,columns=columns)
df

           AAPL    MSFT  TSLA    LULU
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [2]:
df.to_csv("df_example.csv",index_label="Date")

In [7]:
from_csv = pd.read_csv("df_example.csv")
from_csv

       Date   AAPL    MSFT  TSLA    LULU
0  20201201 -0.010  0.0300  0.05  0.0050
1  20201202  0.015  0.0050 -0.05 -0.0025
2  20201203 -0.025  0.0015 -0.02  0.0100
3  20201204 -0.030  0.0150  0.03  0.0100

In [8]:
from_csv.set_index("Date")

           AAPL    MSFT  TSLA    LULU
Date
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100

In [9]:
df.to_excel('df_example.xlsx', index_label="Date")

In [10]:
from_excel = pd.read_excel('df_example.xlsx')
from_excel

       Date   AAPL    MSFT  TSLA    LULU
0  20201201 -0.010  0.0300  0.05  0.0050
1  20201202  0.015  0.0050 -0.05 -0.0025
2  20201203 -0.025  0.0015 -0.02  0.0100
3  20201204 -0.030  0.0150  0.03  0.0100

In [11]:
from_excel.set_index("Date")

           AAPL    MSFT  TSLA    LULU
Date
20201201 -0.010  0.0300  0.05  0.0050
20201202  0.015  0.0050 -0.05 -0.0025
20201203 -0.025  0.0015 -0.02  0.0100
20201204 -0.030  0.0150  0.03  0.0100