In [4]:
import pandas as pd 

# series reindexing
ser=pd.Series({'AAPL':-0.01,'MSFT':-0.02,'TSLA':0.015})
ser

AAPL   -0.010
MSFT   -0.020
TSLA    0.015
dtype: float64

In [5]:
ser.reindex(['TSLA','LULU','AAPL', 'MSFT'])
ser

AAPL   -0.010
MSFT   -0.020
TSLA    0.015
dtype: float64

In [6]:
ser[['TSLA','LULU','AAPL','MSFT']]

KeyError: "['LULU'] not in index"

In [7]:
ser[['TSLA','AAPL','MSFT']]

TSLA    0.015
AAPL   -0.010
MSFT   -0.020
dtype: float64

In [8]:
ser.drop('TSLA')

AAPL   -0.01
MSFT   -0.02
dtype: float64

In [9]:
# DataFrame Reindexing
data = {'AAPL':[-0.01,0.015,-0.025,-0.03],
        'MSFT':[0.03,0.005,0.0015,0.015],
        'TSLA':[0.05,-0.05,-0.2,0.03],
       }

index=['20201201','20201202','20201203','20201204']
df=pd.DataFrame(data,index=index)
df

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201202  0.015  0.0050 -0.05
20201203 -0.025  0.0015 -0.20
20201204 -0.030  0.0150  0.03

In [10]:
new_index = ['20201205','20201204','20201203','20201202','20201201','20201130']
df.reindex(new_index)

           AAPL    MSFT  TSLA
20201205    NaN     NaN   NaN
20201204 -0.030  0.0150  0.03
20201203 -0.025  0.0015 -0.20
20201202  0.015  0.0050 -0.05
20201201 -0.010  0.0300  0.05
20201130    NaN     NaN   NaN

In [11]:
new_columns = ['TSLA','LULU','AAPL','MSFT']
df.reindex(new_index, columns = new_columns)

          TSLA  LULU   AAPL    MSFT
20201205   NaN   NaN    NaN     NaN
20201204  0.03   NaN -0.030  0.0150
20201203 -0.20   NaN -0.025  0.0015
20201202 -0.05   NaN  0.015  0.0050
20201201  0.05   NaN -0.010  0.0300
20201130   NaN   NaN    NaN     NaN

In [13]:
df.loc[new_index, new_columns]

KeyError: "['20201205', '20201130'] not in index"

In [22]:
df

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201202  0.015  0.0050 -0.05
20201203 -0.025  0.0015 -0.20
20201204 -0.030  0.0150  0.03

In [23]:
df.loc[['20201204','20201203','20201202','20201201'], ['TSLA','AAPL','MSFT']]

          TSLA   AAPL    MSFT
20201204  0.03 -0.030  0.0150
20201203 -0.20 -0.025  0.0015
20201202 -0.05  0.015  0.0050
20201201  0.05 -0.010  0.0300

In [25]:
df.drop('20201204')

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201202  0.015  0.0050 -0.05
20201203 -0.025  0.0015 -0.20

In [26]:
df.drop('TSLA', axis = 1)

           AAPL    MSFT
20201201 -0.010  0.0300
20201202  0.015  0.0050
20201203 -0.025  0.0015
20201204 -0.030  0.0150

In [27]:
# series sorting
ser=pd.Series([-0.01,0.02,-0.005,-0.02],index=['20201203','20201202','20201204','20201201'])
ser

20201203   -0.010
20201202    0.020
20201204   -0.005
20201201   -0.020
dtype: float64

In [28]:
ser.sort_index()

20201201   -0.020
20201202    0.020
20201203   -0.010
20201204   -0.005
dtype: float64

In [31]:
ser.sort_index(ascending=False)

20201204   -0.005
20201203   -0.010
20201202    0.020
20201201   -0.020
dtype: float64

In [32]:
ser.sort_values()

20201201   -0.020
20201203   -0.010
20201204   -0.005
20201202    0.020
dtype: float64

In [33]:
# DataFrame Reindexing
data = {'AAPL':[-0.01,0.015,-0.025,-0.03],
        'MSFT':[0.03,0.005,0.0015,0.015],
        'TSLA':[0.05,-0.05,-0.2,0.03],
       }

index=['20201201','20201204','20201203','20201202']
df=pd.DataFrame(data,index=index)
df

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201204  0.015  0.0050 -0.05
20201203 -0.025  0.0015 -0.20
20201202 -0.030  0.0150  0.03

In [34]:
df.sort_index()

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201202 -0.030  0.0150  0.03
20201203 -0.025  0.0015 -0.20
20201204  0.015  0.0050 -0.05

In [35]:
df=df.sort_index(axis=1, ascending=False)
df.sort_index(axis=1)

           AAPL    MSFT  TSLA
20201201 -0.010  0.0300  0.05
20201204  0.015  0.0050 -0.05
20201203 -0.025  0.0015 -0.20
20201202 -0.030  0.0150  0.03

In [38]:
df.sort_values('AAPL')

          TSLA    MSFT   AAPL
20201202  0.03  0.0150 -0.030
20201203 -0.20  0.0015 -0.025
20201201  0.05  0.0300 -0.010
20201204 -0.05  0.0050  0.015